### ISSUE TITLE
escaped characters in output from CRAN package

### ISSUE THREAD

**Issue by al-sharp** [gsucarrat/gets#2] opened 2020-05-13 20:37 UTC
If I install this package (on Linux) from CRAN, v0.23, the printed output from models includes the _literal escape sequences_ for newlines (\n) _instead of_ the desired newlines.  If I install per README.md directions directly from this GitHub repo, I get the desired lovely output with newlines (it sure makes the tables easier to read!)   Possibly this issue belongs in a different repo...

**Comment by gsucarrat** [comment] 2020-07-06 06:39
Hi, sorry for the late reply. We have not been able to identify the exact source of this problem, but we think it is related to which version of R that is used to compile the tarball. Hopefully, the upload of a new version should solve the issue. All the best, Genaro

**Comment by moritzpschwarz** [comment] 2020-07-07 19:22
I think I've found the error: 

in the version that is on CRAN, the `print.arx`and `print.gets` etc. functions use `cat("\\n")` rather than `cat("\n")`. 
See here: https://github.com/cran/gets/blob/fbb9e90754344e068095e4e1dc908a60bdc6e994/R/print.arx.R#L10

From what I can judge, the new version deals with the issue already: 
https://github.com/gsucarrat/gets/blob/d654339dbd2ad062ad00be54a095e3a99d9d8193/gets-base-source.R#L3110

So unless this error is introduced when you upload the package to CRAN, this should be resolved in the next update.

**Comment by gsucarrat** [comment] 2020-07-07 21:28
The problem is that I/we never introduced the double escape. My theory is that it is either R version 4, or its development version (required, in principle, by CRAN when uploading a new version), which introduces the double escape when building the tarball. The tarball on Github has been built with R 3.5.3 64bit under Windows 10, and does not introduce the issue.

**Comment by moritzpschwarz** [comment] 2020-07-31 14:05
The error should be resolved. The new CRAN Version does not show this problem. I will therefore close this issue.

**Closed by moritzpschwarz** 2020-07-31 14:05 UTC
