### ISSUE TITLE
arx(mc=T) causes inconsistent predict() behavior

### ISSUE THREAD

**Issue by mdwy62** [gsucarrat/gets#50] opened 2021-09-17 18:42 UTC
arx(mc=T) will add a constant to the regression but predict() seems to fail to recognize this. It gives an error that the intercept is missing, when provided with the model matrix 
```
# > regTst <- arx(dfi[,wr],mc=TRUE,mxreg=xmm,
# +           vcov.type='white',zero.adj=0,vc.adj=F)
# estimates intercept
# >  head(as.matrix(regTst$aux$mXnames))
#      [,1]              
# [1,] "mconst"          
# [2,] "gender.Male"     
# [3,] "gender.NonBinary"
# [4,] "rcethn.Black"    
# [5,] "rcethn.Other"    
# [6,] "rcethn.Hispanic" 
# > prdTst <- predict(regTst,n.ahead=nrow(xmm),newmxreg=xmm)
# no error in prediction
# 
# replace mc = TRUE with mc=T
# > regTst <- arx(dfi[,wr],mc=T,mxreg=xmm,
# +           vcov.type='white',zero.adj=0,vc.adj=F)
# intercept included 
# >  head(as.matrix(regTst$aux$mXnames))
#      [,1]              
# [1,] "mconst"          
# [2,] "gender.Male"     
# [3,] "gender.NonBinary"
# [4,] "rcethn.Black"    
# [5,] "rcethn.Other"    
# [6,] "rcethn.Hispanic" 
# > prdTst <- predict(regTst,n.ahead=nrow(xmm),newmxreg=xmm)
# Error in newmxreg %*% as.numeric(coefs[mxregIndx]) : 
#   non-conformable arguments

```

**Comment by moritzpschwarz** [comment] 2021-09-17 20:49
Thanks for pointing this out @mdwy62 !! This is clearly something we need to deal with.

A reproduceable example here: 

```r
set.seed(123)
y <- arima.sim(list(ar=0.4), 70)
xregs <- matrix(rnorm(4*70), 70, 4)

m1 <- arx(y, ar=1:2, mxreg=xregs, mc = TRUE)
pred.m1 <- predict(m1,n.ahead=nrow(xregs),newmxreg=xregs)

m2 <- arx(y, ar=1:2, mxreg=xregs, mc = T)
pred.m2 <- predict(m2,n.ahead=nrow(xregs),newmxreg=xregs)
```

@gsucarrat I traced this back to here: 

https://github.com/gsucarrat/gets/blob/21ddee5ffe6a9d36b14c87c00f9f55c55b8a78f2/gets/R/gets-base-source.R#L3301

where the `isTRUE()` fails when checking whether the `object$call$mc` is `TRUE` - but actually the value is not a logical value but actually just a "symbol"...

The value that is stored by `object$call$mc` is the output from `sys.call()`:

https://github.com/gsucarrat/gets/blob/21ddee5ffe6a9d36b14c87c00f9f55c55b8a78f2/gets/R/gets-base-source.R#L2269
Which is added to the output arx object here:
https://github.com/gsucarrat/gets/blob/21ddee5ffe6a9d36b14c87c00f9f55c55b8a78f2/gets/R/gets-base-source.R#L2464

The reason for this error is that `sys.call()` does not save the `T` as a logical value but rather as a `symbol`. Consider this: 

```r
test_fun <- function(x, mc){
  out <- list()
  out$a <- rnorm(x)
  out$call <- sys.call()
  out$call_2 <- match.call() # also trying out match.call
  return(out)
}

main_example <- test_fun(2, mc = T)
main_example$sys_call$mc # showing T
main_example$match_call$mc # showing T

main_example$sys_call$mc == TRUE # resulting in FALSE
main_example$match_call$mc == TRUE # resulting in FALSE
isTRUE(main_example$sys_call$mc) # resulting in FALSE
isTRUE(main_example$match_call$mc) # resulting in FALSE

str(main_example$sys_call$mc) # showing that T is a symbol, not logical
str(main_example$match_call$mc) # showing that T is a symbol, not logical
```

We could aim to replace all elements in the `call` element with something like this: 
```r
is.symbol(main_example$sys_call$mc) && main_example$sys_call$mc == as.symbol("T")
```

or even this would work: 

```r
isTRUE(eval(test_fun(2, T)$sys_call[[3]]))
```

or if we switched to `match.call()`: 

```r
isTRUE(eval(test_fun(2, T)$match_call$mc))
```

**Comment by mdwy62** [comment] 2021-09-18 02:53
Since T is a variable, perhaps more generally passing in a variable that is logical, e.g.,  mc=AddInt would be problematic for predict as well.

From ?logical
     'TRUE' and 'FALSE' are reserved words denoting logical constants
     in the R language, whereas 'T' and 'F' are global variables whose
     initial values set to these.  All four are 'logical(1)' vectors.

**Comment by moritzpschwarz** [comment] 2021-09-19 13:06
Very true!

```r
AddInt <- TRUE
m3 <- arx(y, ar=1:2, mxreg=xregs, mc = AddInt)
pred.m3 <- predict(m3,n.ahead=nrow(xregs),newmxreg=xregs) # fail

m3$call$mc
```

 perhaps this could work: 
```r
eval(m3$call$mc)
```

**Comment by gsucarrat** [comment] 2021-09-29 09:43
Thanks a lot [mdwy62](https://github.com/mdwy62)! The issue should be fixed now in the new development version (29 September 2021) of the package.

**Closed by gsucarrat** 2021-09-29 09:43 UTC
